site_name: "/lost+found/"
site_url: "https://rmic.github.io/"
site_description: "A stash of ideas, side quests, and near misses."

plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_date_format: medium
      post_url_format: "{slug}"
  - meta
  - tags
  - search

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - search.suggest
    - search.highlight

  palette: 
  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
    - abbr
    - admonition
    - pymdownx.details
    - pymdownx.superfences

nav:
  - Home: index.md
  - "AI": /category/ai/
  - "Data": /category/data/
  - "Software Engineering": /category/software-engineering/
  - "git tricks": /category/git-tricks/
  - "Misc": /category/misc/

extra_css:
  - stylesheets/extra.css