site_name: "rmic"
site_url: "https://rmic.github.io/"

plugins:
  - blog:
      blog_toc: true
      post_date_format: medium
      post_url_format: "{slug}"
  - meta
  - tags
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - search.highlight
    - content.code.annotate
    - content.code.copy
nav:
- Home: index.md
- Blog:
    - "Latest Posts": blog/index.md